### ISSUE TITLE
The resulting tiff is not valid - cannot be opened by ImageJ nor MATLAB imread

### ISSUE THREAD

**Issue by CreLox** [rharkes/Fast_Tiff_Write#1] opened 2019-11-13 20:49 UTC
I used MATLAB R2019a Update 6 (on macOS Sierra 10.12.6) to run the included test_fTiff.m. The resulting test.tif cannot be read by ImageJ (only the first frame is recognized). MATLAB 'imread' gives the following error:
Unable to read TIFF file "test.tif". File is corrupt or image does not contain any readable strips.

**Comment by rharkes** [comment] 2020-03-24 08:32
Thank you for reporting this issue. I will try to reproduce it on windows 10 with matlab 2019a, but unfortunately I do not have macOS.

**Comment by rharkes** [comment] 2020-03-26 13:19
The cause of this issue is that compression was not working correctly for multi page tiff it seems. It should be fixed in version 2.1.

**Closed as completed by rharkes** 2020-03-26 13:19 UTC
